services:
  playwright:
    build: .
    volumes:
      - ./:/usr/workspace
    working_dir: /usr/workspace
    env_file:
      - .env
#    Постоянно запущенный контейнер
#    stdin_open: true
#    tty: true
    command: uv run pytest --alluredir=allure-results tests/ui/test_hubid.py::TestHubID::test_email_registration_from_auth[dev]

