[pytest]
asyncio_mode = auto
addopts = --dist loadgroup
markers =
    smoke: Быстрые smoke-тесты
    regression: Полный регрессионный набор

    critical: Критически важные тесты
    medium: Средней важности тесты
    
    hubid: Тесты авторизации и регистрации
    vacancy: Тесты вакансий
    events: Тесты мероприятий
    hubmarket: Тесты Hub Market

    api: API тесты
    ui: UI тесты
    

    ; --dist loadscope ------ по классам 
    ; --dist loadgroup ---- по группа
    ; @pytest.mark.xdist_group("events_favorite")
