[pytest]
asyncio_mode = auto
markers =
    smoke: Быстрые smoke-тесты
    regression: Полный регрессионный набор
    critical: Критически важные тесты
    
    hubid: Тесты авторизации и регистрации
    vacancy: Тесты вакансий
    events: Тесты мероприятий
    hubmarket: Тесты Hub Market

    api: API тесты
    ui: UI тесты
    