class Links:
    HOST = 'https://dev.astanahub.com'
    ACCOUNT_SETTING = f'{HOST}/account/settings/'
    ARM = 'https://arm-dev.astanahub.com'
    ACCREDITATION_RENEWAL_FL = f'{HOST}/account/service/Accreditation-for-phys/request/299/create/'
    ACCREDITATION_RENEWAL_UL = f'{HOST}/account/service/Accreditation-for-ur/request/351/create/'
    ACCREDITATION_DUBLICATE_FL = f'{HOST}/account/service/Accreditationdubl2/request/361/create/'
    ACCREDITATION_DUBLICATE_UL = f'{HOST}/account/service/Accreditationdubl3/request/359/create/'
    ACCREDITATION_FL = f'{HOST}/account/service/indivAccreditation/request/245/create/'
    ACCREDITATION_UL = f'{HOST}/account/service/accreditationJL/request/206/create/'
    LOGIN_PAGE = f'{HOST}/ru/s/auth/login/'
