name: run-and-upload-to-testops

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: 'TestOps service parameter. Leave blank'
        required: false
      ALLURE_USERNAME:
        description: 'TestOps service parameter. Leave blank'
        required: false

env:
  ALLURE_ENDPOINT: https://astanahub.testops.cloud
  ALLURE_PROJECT_ID: 1
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: allure-results

jobs:
  all-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Установка uv
      - name: Install uv
        run: pip install uv

      # Установка зависимостей из твоего pyproject.toml / uv.lock
      - name: Install dependencies
        run: uv sync

      # Установка браузеров Playwright
      - name: Install Playwright browsers
        run: uv run playwright install chromium --with-deps

      # Установка allurectl
      - uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: https://astanahub.testops.cloud
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: 1

      # Запуск тестов с передачей результатов в TestOps
      - name: Run tests
        run: allurectl watch -- uv run pytest ./tests --alluredir=allure-results || true
        env:
          ALLURE_RESULTS: allure-results
