name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    # Python с автоматическим кешированием pip зависимостей
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        cache: 'pip'
        cache-dependency-path: 'requirements.txt'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Получаем версию Playwright правильным способом
    - name: Get Playwright version
      id: playwright-version
      run: |
        PLAYWRIGHT_VERSION=$(pip show playwright | grep Version | cut -d' ' -f2)
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    # Установка браузеров если нет кэша
    - name: Install Playwright browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: python -m playwright install --with-deps

    - name: Install Playwright OS dependencies
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: python -m playwright install-deps

    - name: Run your tests
      run: pytest --alluredir=allure-results --tracing=retain-on-failure
      continue-on-error: true

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/

    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
    - name: Download Allure results
      uses: actions/download-artifact@v4
      with:
        name: allure-results
        path: allure-results

    - name: Checkout gh-pages branch for history
      uses: actions/checkout@v5
      with:
        ref: gh-pages
        path: gh-pages
      continue-on-error: true

    - name: Copy Allure history to current results
      run: |
        if [ -d "gh-pages/allure-report/history" ]; then
          mkdir -p allure-results/history
          cp -r gh-pages/allure-report/history/* allure-results/history/
        fi

    - name: Install Allure CLI
      run: |
        ALLURE_VERSION=2.24.1
        wget https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.zip
        unzip allure-${ALLURE_VERSION}.zip -d $HOME/.allure
        echo "$HOME/.allure/allure-${ALLURE_VERSION}/bin" >> $GITHUB_PATH


    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Parse Allure report stats
      run: |
        sudo apt-get update && sudo apt-get install -y jq
        STAT_JSON=$(cat allure-report/widgets/summary.json)
        PASSED=$(echo "$STAT_JSON" | jq .passed)
        FAILED=$(echo "$STAT_JSON" | jq .failed)
        BROKEN=$(echo "$STAT_JSON" | jq .broken)
        SKIPPED=$(echo "$STAT_JSON" | jq .skipped)
        UNKNOWN=$(echo "$STAT_JSON" | jq .unknown)
        TOTAL=$(echo "$STAT_JSON" | jq .total)
        
        echo "PASSED=$PASSED" >> $GITHUB_ENV
        echo "FAILED=$FAILED" >> $GITHUB_ENV
        echo "BROKEN=$BROKEN" >> $GITHUB_ENV
        echo "SKIPPED=$SKIPPED" >> $GITHUB_ENV
        echo "UNKNOWN=$UNKNOWN" >> $GITHUB_ENV
        echo "TOTAL=$TOTAL" >> $GITHUB_ENV
        

    - name: Deploy report to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report

    - name: Send report to Telegram
      run: |
        REPORT_URL="https://${{ github.repository_owner }}.github.io/${{ github.repository }}/"
        TEXT="Allure report updated: $REPORT_URL\nPassed: $PASSED, Failed: $FAILED, Broken: $BROKEN, Skipped: $SKIPPED"
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TG_CHAT_ID }}" \
          -d text="$TEXT"